### ISSUE TITLE
Disable renovate for go dependencies

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kyverno-dsl-policy#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Renovate bot tries to update dependencies, this could cause the build to fail and the dependencies going out of sync with the vendored third party packages.

### Expected Behavior

We should disable the renovate bot updates for golang dependencies and keep the ones for the github actions.

**Comment by viccuad** [comment]
Agree too.

**Comment by fabriziosestito** [comment]
> We could create a custom updatecli job that checks for new releases of kyverno

@flavio collected in a new issue: https://github.com/kubewarden/kyverno-dsl-policy/issues/24
